// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXqeMjQe_RUoBZ_zM9_eS5QSPIX8ICFoU',
    appId: '1:525564474419:web:ea242cff51abb79407df46',
    messagingSenderId: '525564474419',
    projectId: 'sndpowerapp',
    authDomain: 'sndpowerapp.firebaseapp.com',
    storageBucket: 'sndpowerapp.firebasestorage.app',
    measurementId: 'G-2D0BZ5R8RS',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ2Pftt506CopCKMlfP4_rOzDQmPZf8bo',
    appId: '1:525564474419:ios:e2761bda3f7fa93607df46',
    messagingSenderId: '525564474419',
    projectId: 'sndpowerapp',
    storageBucket: 'sndpowerapp.firebasestorage.app',
    iosBundleId: 'com.alsanidi.companyPortal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXqeMjQe_RUoBZ_zM9_eS5QSPIX8ICFoU',
    appId: '1:525564474419:web:e1ba6a04dee82d5207df46',
    messagingSenderId: '525564474419',
    projectId: 'sndpowerapp',
    authDomain: 'sndpowerapp.firebaseapp.com',
    storageBucket: 'sndpowerapp.firebasestorage.app',
    measurementId: 'G-NHLE3JC179',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ2Pftt506CopCKMlfP4_rOzDQmPZf8bo',
    appId: '1:525564474419:ios:95c8fa009d19b93e07df46',
    messagingSenderId: '525564474419',
    projectId: 'sndpowerapp',
    storageBucket: 'sndpowerapp.firebasestorage.app',
    iosBundleId: 'com.alsanidi.companyPortal.RunnerTests',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgIziVFGiz_Vq0lLWSozKnTI_Yttl3O8M',
    appId: '1:525564474419:android:0424128053b7df5a07df46',
    messagingSenderId: '525564474419',
    projectId: 'sndpowerapp',
    storageBucket: 'sndpowerapp.firebasestorage.app',
  );

}